/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  subtitle?: string;
  image?: ImageWithAlt;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  excerpt?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  placeholder?: string;
  credit?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Publication = {
  _id: string;
  _type: "publication";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  reference?: string;
  year?: string;
  kind?: "artigo" | "livro" | "capitulo";
  url?: string;
  authors?: Array<string>;
};

export type Locality = {
  _id: string;
  _type: "locality";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  shortName?: string;
  description?: string;
  image?: ImageWithAlt;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  orderRank?: string;
};

export type LocalityReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "locality";
};

export type Species = {
  _id: string;
  _type: "species";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  scientificName?: string;
  slug?: Slug;
  commonNames?: Array<string>;
  group?: "anfibio" | "reptil";
  ordem?:
    | "Anura"
    | "Caudata"
    | "Gymnophiona"
    | "Squamata"
    | "Testudines"
    | "Crocodylia";
  familia?: string;
  subfamilia?: string;
  localities?: Array<
    {
      _key: string;
    } & LocalityReference
  >;
  habitat?: string;
  description?: string;
  reproduction?: string;
  distribution?: string;
  threatStatus?: "LC" | "NT" | "VU" | "EN" | "CR" | "DD" | "NE";
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  references?: string;
  image?: ImageWithAlt;
  gallery?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  audioUrl?: string;
  videoUrl?: string;
};

export type News = {
  _id: string;
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: string;
  publishedAt?: string;
  image?: ImageWithAlt;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  origin?: "noticia" | "publicacao";
  excerpt?: string;
};

export type GalleryItem = {
  _id: string;
  _type: "galleryItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: ImageWithAlt;
  caption?: string;
  stamp?: string;
  orderRank?: string;
};

export type Coordinator = {
  _id: string;
  _type: "coordinator";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  image?: ImageWithAlt;
  caption?: string;
  bio?: string;
  lines?: string;
  email?: string;
  lattes?: string;
  orderRank?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  number?: string;
  status?: "em campo" | "em an\xE1lise" | "conclu\xEDdo";
  description?: string;
  image?: ImageWithAlt;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  bioma?: string;
  taxonCientifico?: string;
  taxonPopular?: Array<string>;
  responsavel?: string;
  periodoInicio?: string;
  periodoFim?: string;
  financiador?: string;
  orderRank?: string;
};

export type SectionHead = {
  _id: string;
  _type: "sectionHead";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  key?:
    | "news"
    | "newsArchive"
    | "projects"
    | "coordinators"
    | "gallery"
    | "contact";
  kicker?: string;
  title?: string;
  blurb?: string;
};

export type ContactSection = {
  _id: string;
  _type: "contactSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  body?: string;
  rows?: Array<
    {
      _key: string;
    } & ContactRow
  >;
  form?: {
    heading?: string;
    nameLabel?: string;
    namePlaceholder?: string;
    orgLabel?: string;
    orgPlaceholder?: string;
    emailLabel?: string;
    emailPlaceholder?: string;
    subjectLabel?: string;
    subjectOptions?: Array<{
      value?: string;
      label?: string;
      _type: "subjectOption";
      _key: string;
    }>;
    messageLabel?: string;
    messagePlaceholder?: string;
    note?: string;
    submitLabel?: string;
    sendingLabel?: string;
    sentLabel?: string;
    sentMessage?: string;
  };
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    eyebrow?: string;
    titleLines?: Array<string>;
    squiggleWord?: string;
    lede?: string;
    ctas?: Array<
      {
        _key: string;
      } & Link
    >;
    margin?: string;
    polaroid?: {
      image?: ImageWithAlt;
      caption?: string;
      stamp?: string;
    };
  };
  stats?: Array<{
    num?: string;
    lbl?: string;
    _type: "stat";
    _key: string;
  }>;
  manifesto?: {
    quote?: string;
    sig?: string;
  };
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brandName?: string;
  brandTag?: string;
  navLinks?: Array<
    {
      _key: string;
    } & NavLink
  >;
  footerText?: string;
  footerColumns?: Array<{
    title?: string;
    links?: Array<
      {
        _key: string;
      } & Link
    >;
    _type: "footerColumn";
    _key: string;
  }>;
  footerFine?: Array<string>;
};

export type ContactRow = {
  _type: "contactRow";
  label?: string;
  value?: string;
  note?: string;
};

export type NavLink = {
  _type: "navLink";
  label?: string;
  href?: string;
  pin?: boolean;
};

export type Link = {
  _type: "link";
  label?: string;
  href?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Page
  | SanityImageAssetReference
  | ImageWithAlt
  | Slug
  | Publication
  | Locality
  | LocalityReference
  | Species
  | News
  | GalleryItem
  | Coordinator
  | Project
  | SectionHead
  | ContactSection
  | HomePage
  | SiteSettings
  | ContactRow
  | NavLink
  | Link
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: lib/sanity/queries.ts
// Variable: siteUpdatedAtQuery
// Query: *[_type in ["siteSettings", "homePage", "contactSection", "sectionHead",    "project", "coordinator", "galleryItem", "news"]]  | order(_updatedAt desc)[0]._updatedAt
export type SiteUpdatedAtQueryResult = string | null;

// Source: lib/sanity/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]{  brandName,  brandTag,  navLinks[]{ label, href, pin },  footerText,  footerColumns[]{ title, links[]{ label, href } },  footerFine}
export type SiteSettingsQueryResult = {
  brandName: string | null;
  brandTag: string | null;
  navLinks: Array<{
    label: string | null;
    href: string | null;
    pin: boolean | null;
  }> | null;
  footerText: string | null;
  footerColumns: Array<{
    title: string | null;
    links: Array<{
      label: string | null;
      href: string | null;
    }> | null;
  }> | null;
  footerFine: Array<string> | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: homePageQuery
// Query: *[_type == "homePage"][0]{  hero{    margin,    eyebrow,    titleLines,    squiggleWord,    lede,    ctas[]{ label, href },    polaroid{      caption,      stamp,      image{        alt,        placeholder,        image{ ..., asset->{ _id, metadata { dimensions, lqip } } }      }    }  },  stats[]{ num, lbl },  manifesto{ quote, sig }}
export type HomePageQueryResult = {
  hero: {
    margin: string | null;
    eyebrow: string | null;
    titleLines: Array<string> | null;
    squiggleWord: string | null;
    lede: string | null;
    ctas: Array<{
      label: string | null;
      href: string | null;
    }> | null;
    polaroid: {
      caption: string | null;
      stamp: string | null;
      image: {
        alt: string | null;
        placeholder: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: SanityImageDimensions | null;
              lqip: string | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
      } | null;
    } | null;
  } | null;
  stats: Array<{
    num: string | null;
    lbl: string | null;
  }> | null;
  manifesto: {
    quote: string | null;
    sig: string | null;
  } | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: sectionHeadsQuery
// Query: *[_type == "sectionHead"]{  key,  kicker,  title,  blurb}
export type SectionHeadsQueryResult = Array<{
  key:
    | "contact"
    | "coordinators"
    | "gallery"
    | "news"
    | "newsArchive"
    | "projects"
    | null;
  kicker: string | null;
  title: string | null;
  blurb: string | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: projectsQuery
// Query: *[_type == "project" && defined(slug.current)]  | order(orderRank){  _id,  _updatedAt,  number,  status,  title,  "slug": slug.current,  description,  bioma,  responsavel,  periodoInicio,  periodoFim,  financiador,  image{    alt,    placeholder,    image{ ..., asset->{ _id, metadata { dimensions, lqip } } }  }}
export type ProjectsQueryResult = Array<{
  _id: string;
  _updatedAt: string;
  number: string | null;
  status: "conclu\xEDdo" | "em an\xE1lise" | "em campo" | null;
  title: string | null;
  slug: string | null;
  description: string | null;
  bioma: string | null;
  responsavel: string | null;
  periodoInicio: string | null;
  periodoFim: string | null;
  financiador: string | null;
  image: {
    alt: string | null;
    placeholder: string | null;
    image: {
      asset: {
        _id: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: projectBySlugQuery
// Query: *[_type == "project" && slug.current == $slug][0]{  _id,  _updatedAt,  number,  status,  title,  "slug": slug.current,  description,  bioma,  taxonCientifico,  taxonPopular,  responsavel,  periodoInicio,  periodoFim,  financiador,  body,  image{    alt,    placeholder,    image{ ..., asset->{ _id, metadata { dimensions, lqip } } }  }}
export type ProjectBySlugQueryResult = {
  _id: string;
  _updatedAt: string;
  number: string | null;
  status: "conclu\xEDdo" | "em an\xE1lise" | "em campo" | null;
  title: string | null;
  slug: string | null;
  description: string | null;
  bioma: string | null;
  taxonCientifico: string | null;
  taxonPopular: Array<string> | null;
  responsavel: string | null;
  periodoInicio: string | null;
  periodoFim: string | null;
  financiador: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  image: {
    alt: string | null;
    placeholder: string | null;
    image: {
      asset: {
        _id: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: pagesQuery
// Query: *[_type == "page" && defined(slug.current)]  | order(title asc){  _id,  _updatedAt,  title,  "slug": slug.current,  subtitle,  excerpt}
export type PagesQueryResult = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  subtitle: string | null;
  excerpt: string | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: pageBySlugQuery
// Query: *[_type == "page" && slug.current == $slug][0]{  _id,  _updatedAt,  title,  "slug": slug.current,  subtitle,  excerpt,  body,  image{    alt,    placeholder,    image{ ..., asset->{ _id, metadata { dimensions, lqip } } }  }}
export type PageBySlugQueryResult = {
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  subtitle: string | null;
  excerpt: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  image: {
    alt: string | null;
    placeholder: string | null;
    image: {
      asset: {
        _id: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: coordinatorsQuery
// Query: *[_type == "coordinator"] | order(orderRank){  _id,  name,  role,  caption,  bio,  lines,  image{    alt,    placeholder,    image{ ..., asset->{ _id, metadata { dimensions, lqip } } }  }}
export type CoordinatorsQueryResult = Array<{
  _id: string;
  name: string | null;
  role: string | null;
  caption: string | null;
  bio: string | null;
  lines: string | null;
  image: {
    alt: string | null;
    placeholder: string | null;
    image: {
      asset: {
        _id: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: galleryQuery
// Query: *[_type == "galleryItem"] | order(orderRank){  _id,  caption,  stamp,  image{    alt,    placeholder,    image{ ..., asset->{ _id, metadata { dimensions, lqip } } }  }}
export type GalleryQueryResult = Array<{
  _id: string;
  caption: string | null;
  stamp: string | null;
  image: {
    alt: string | null;
    placeholder: string | null;
    image: {
      asset: {
        _id: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: contactSectionQuery
// Query: *[_type == "contactSection"][0]{  heading,  body,  rows[]{ label, value, note },  form{    heading,    nameLabel, namePlaceholder,    orgLabel, orgPlaceholder,    emailLabel, emailPlaceholder,    subjectLabel, subjectOptions[]{ value, label },    messageLabel, messagePlaceholder,    note, submitLabel, sendingLabel, sentLabel, sentMessage  }}
export type ContactSectionQueryResult = {
  heading: string | null;
  body: string | null;
  rows: Array<{
    label: string | null;
    value: string | null;
    note: string | null;
  }> | null;
  form: {
    heading: string | null;
    nameLabel: string | null;
    namePlaceholder: string | null;
    orgLabel: string | null;
    orgPlaceholder: string | null;
    emailLabel: string | null;
    emailPlaceholder: string | null;
    subjectLabel: string | null;
    subjectOptions: Array<{
      value: string | null;
      label: string | null;
    }> | null;
    messageLabel: string | null;
    messagePlaceholder: string | null;
    note: string | null;
    submitLabel: string | null;
    sendingLabel: string | null;
    sentLabel: string | null;
    sentMessage: string | null;
  } | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: allNewsQuery
// Query: *[_type == "news" && defined(slug.current)]  | order(publishedAt desc){  _id,  _updatedAt,  title,  "slug": slug.current,  author,  publishedAt,  excerpt,  body,  image{    alt,    placeholder,    image{ ..., asset->{ _id, metadata { dimensions, lqip } } }  }}
export type AllNewsQueryResult = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  author: string | null;
  publishedAt: string | null;
  excerpt: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  image: {
    alt: string | null;
    placeholder: string | null;
    image: {
      asset: {
        _id: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: recentNewsQuery
// Query: *[_type == "news" && defined(slug.current)]  | order(publishedAt desc)[0...$limit]{  _id,  _updatedAt,  title,  "slug": slug.current,  author,  publishedAt,  excerpt,  body,  image{    alt,    placeholder,    image{ ..., asset->{ _id, metadata { dimensions, lqip } } }  }}
export type RecentNewsQueryResult = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  author: string | null;
  publishedAt: string | null;
  excerpt: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  image: {
    alt: string | null;
    placeholder: string | null;
    image: {
      asset: {
        _id: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: newsBySlugQuery
// Query: *[_type == "news" && slug.current == $slug][0]{  _id,  _updatedAt,  title,  "slug": slug.current,  author,  publishedAt,  excerpt,  body,  image{    alt,    placeholder,    image{ ..., asset->{ _id, metadata { dimensions, lqip } } }  }}
export type NewsBySlugQueryResult = {
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  author: string | null;
  publishedAt: string | null;
  excerpt: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  image: {
    alt: string | null;
    placeholder: string | null;
    image: {
      asset: {
        _id: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type in ["siteSettings", "homePage", "contactSection", "sectionHead",\n    "project", "coordinator", "galleryItem", "news"]]\n  | order(_updatedAt desc)[0]._updatedAt': SiteUpdatedAtQueryResult;
    '*[_type == "siteSettings"][0]{\n  brandName,\n  brandTag,\n  navLinks[]{ label, href, pin },\n  footerText,\n  footerColumns[]{ title, links[]{ label, href } },\n  footerFine\n}': SiteSettingsQueryResult;
    '*[_type == "homePage"][0]{\n  hero{\n    margin,\n    eyebrow,\n    titleLines,\n    squiggleWord,\n    lede,\n    ctas[]{ label, href },\n    polaroid{\n      caption,\n      stamp,\n      image{\n        alt,\n        placeholder,\n        image{ ..., asset->{ _id, metadata { dimensions, lqip } } }\n      }\n    }\n  },\n  stats[]{ num, lbl },\n  manifesto{ quote, sig }\n}': HomePageQueryResult;
    '*[_type == "sectionHead"]{\n  key,\n  kicker,\n  title,\n  blurb\n}': SectionHeadsQueryResult;
    '*[_type == "project" && defined(slug.current)]\n  | order(orderRank){\n  _id,\n  _updatedAt,\n  number,\n  status,\n  title,\n  "slug": slug.current,\n  description,\n  bioma,\n  responsavel,\n  periodoInicio,\n  periodoFim,\n  financiador,\n  image{\n    alt,\n    placeholder,\n    image{ ..., asset->{ _id, metadata { dimensions, lqip } } }\n  }\n}': ProjectsQueryResult;
    '*[_type == "project" && slug.current == $slug][0]{\n  _id,\n  _updatedAt,\n  number,\n  status,\n  title,\n  "slug": slug.current,\n  description,\n  bioma,\n  taxonCientifico,\n  taxonPopular,\n  responsavel,\n  periodoInicio,\n  periodoFim,\n  financiador,\n  body,\n  image{\n    alt,\n    placeholder,\n    image{ ..., asset->{ _id, metadata { dimensions, lqip } } }\n  }\n}': ProjectBySlugQueryResult;
    '*[_type == "page" && defined(slug.current)]\n  | order(title asc){\n  _id,\n  _updatedAt,\n  title,\n  "slug": slug.current,\n  subtitle,\n  excerpt\n}': PagesQueryResult;
    '*[_type == "page" && slug.current == $slug][0]{\n  _id,\n  _updatedAt,\n  title,\n  "slug": slug.current,\n  subtitle,\n  excerpt,\n  body,\n  image{\n    alt,\n    placeholder,\n    image{ ..., asset->{ _id, metadata { dimensions, lqip } } }\n  }\n}': PageBySlugQueryResult;
    '*[_type == "coordinator"] | order(orderRank){\n  _id,\n  name,\n  role,\n  caption,\n  bio,\n  lines,\n  image{\n    alt,\n    placeholder,\n    image{ ..., asset->{ _id, metadata { dimensions, lqip } } }\n  }\n}': CoordinatorsQueryResult;
    '*[_type == "galleryItem"] | order(orderRank){\n  _id,\n  caption,\n  stamp,\n  image{\n    alt,\n    placeholder,\n    image{ ..., asset->{ _id, metadata { dimensions, lqip } } }\n  }\n}': GalleryQueryResult;
    '*[_type == "contactSection"][0]{\n  heading,\n  body,\n  rows[]{ label, value, note },\n  form{\n    heading,\n    nameLabel, namePlaceholder,\n    orgLabel, orgPlaceholder,\n    emailLabel, emailPlaceholder,\n    subjectLabel, subjectOptions[]{ value, label },\n    messageLabel, messagePlaceholder,\n    note, submitLabel, sendingLabel, sentLabel, sentMessage\n  }\n}': ContactSectionQueryResult;
    '*[_type == "news" && defined(slug.current)]\n  | order(publishedAt desc){\n  _id,\n  _updatedAt,\n  title,\n  "slug": slug.current,\n  author,\n  publishedAt,\n  excerpt,\n  body,\n  image{\n    alt,\n    placeholder,\n    image{ ..., asset->{ _id, metadata { dimensions, lqip } } }\n  }\n}': AllNewsQueryResult;
    '*[_type == "news" && defined(slug.current)]\n  | order(publishedAt desc)[0...$limit]{\n  _id,\n  _updatedAt,\n  title,\n  "slug": slug.current,\n  author,\n  publishedAt,\n  excerpt,\n  body,\n  image{\n    alt,\n    placeholder,\n    image{ ..., asset->{ _id, metadata { dimensions, lqip } } }\n  }\n}': RecentNewsQueryResult;
    '*[_type == "news" && slug.current == $slug][0]{\n  _id,\n  _updatedAt,\n  title,\n  "slug": slug.current,\n  author,\n  publishedAt,\n  excerpt,\n  body,\n  image{\n    alt,\n    placeholder,\n    image{ ..., asset->{ _id, metadata { dimensions, lqip } } }\n  }\n}': NewsBySlugQueryResult;
  }
}
